[package]
name    = "nonagon"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "GPLv3"

[dependencies]
image           = "*"
docopt          = "*"
docopt_macros   = "*"
rustc-serialize = "*"
log             = "*"
env_logger      = "*"

[dependencies.ffmpeg]
version = "0.1"

default-features = false
features         = ["codec", "format", "software-scaling", "software-resampling"]

[dependencies.openal]
version = "0.1"

[dependencies.glium]
version  = "*"
features = ["image"]
