[package]
name    = "nonagon"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "GPLv3"

[dependencies]
cpal            = "*"
image           = "*"
docopt          = "*"
docopt_macros   = "*"
rustc-serialize = "*"
log             = "*"
env_logger      = "*"

[dependencies.ffmpeg]
path = "../ffmpeg"

default-features = false
features         = ["codec", "format", "software-scaling"]

[dependencies.glium]
version  = "*"
features = ["image"]
