[package]
name    = "nonagon"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "GPLv3"

[dependencies]
log        = "*"
env_logger = "*"

docopt = "*"

image = "*"

nalgebra = "*"
ncollide = "*"

[dependencies.ffmpeg]
#version = "0.1"
path = "../ffmpeg"

default-features = false
features         = ["codec", "format", "software-scaling", "software-resampling"]

[dependencies.openal]
#version = "0.1"
path = "../openal"

[dependencies.glium]
version  = "*"

default-features = false
features         = ["glutin", "image", "nalgebra"]
