[game]
step = 0.015

[game.window.16-9]
width  = 640
height = 360

[game.ship]
shape  = "tetrahedron"
face   = "#ff69b4"
border = "#000"

[audio]
only = false
mute = false

[video]
vsync         = true
multisampling = false

[video.texture.filtering.ship]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.texture.filtering.background]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.effects.bullet.plasma]
glow = true

[analyzer.window]
# number of samples in every window
size = 1024

# number of overlapping samples
hop = 512

# make the window a hamming window
hamming = true

[analyzer.beat]
# ignore the missing bands
ignore-missing = true

[analyzer.beat.threshold]
# samples of look-ahead and look-behind for the threshold, about a
# second worth of samples.
size = 25

# default magic number from the gods
sensitivity = 1.5

[[analyzer.beat.band]]
name        = "kick"
range       = [50, 500]
sensitivity = 1.3

[[analyzer.beat.band]]
name        = "snare"
range       = [100, 240]
sensitivity = 1.4
