[game.window.16-9]
width  = 640
height = 360

[game.ship]
shape  = "tetrahedron"
face   = "#ff69b4"
border = "#000"

[audio]
only = false
mute = false

[video]
vsync         = true
multisampling = false

[video.texture.filtering.ship]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.texture.filtering.background]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.effects.bullet.plasma]
glow = true

[analyzer.window]
# number of samples in every window
size = 1024

# number of overlapping samples
hop = 512

# make the window a hamming window
hamming = true

[analyzer.beat.threshold]
# samples of look-ahead and look-behind for the threshold, about a
# second worth of samples.
size = 25

# magic number from the gods
sensitivity = 1.5

[[analyzer.beat.band]]
# the band frequency range
range = [80, 4000]

# a custom sensitivity for this band
sensitivity = 2.0

[[analyzer.beat.band]]
# the band frequency range
range = [4000, 10000]

# a custom sensitivity for this band
sensitivity = 2.0

[[analyzer.beat.band]]
# the band frequency range
range = [10000, 16000]

# a custom sensitivity for this band
sensitivity = 2.0
