[game]
step = 0.015

[game.window.16-9]
width  = 640
height = 360

[game.ship]
shape  = "tetrahedron"
face   = "#ff69b4"
border = "#000"

[audio]
only  = false
music = true

[video]
vsync         = true
multisampling = false

[video.texture.filtering.ship]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.texture.filtering.background]
minify     = "linear"
magnify    = "linear"
anisotropy = 16

[video.effects.bullet.plasma]
glow = true

[analyzer.window]
# number of samples in every window
size = 1024

# number of overlapping samples
hop = 512

# specify what filter to use for the window
filter = "hamming"

[analyzer.beat]
# the amount of seconds after a beat where beats are ignored
throttle = 0.25

[analyzer.beat.threshold]
# number of samples behind and in front of the current, about one second worth
size = 25

# magic number from the gods
sensitivity = 1.5
